// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dal

type App struct {
	AppID      string `json:"app_id"`
	ImgUrl     string `json:"img_url"`
	Registered bool   `json:"registered"`
}

type MonitorBlock struct {
	Event    string `json:"event"`
	BlockNum int64  `json:"block_num"`
	BlockIdx int64  `json:"block_idx"`
	Restart  bool   `json:"restart"`
}

type MyBid struct {
	ReqID              string `json:"req_id"`
	MyFee              string `json:"my_fee"`
	BidNonce           string `json:"bid_nonce"`
	ShouldRevealAfter  int64  `json:"should_reveal_after"`
	ShouldRevealBefore int64  `json:"should_reveal_before"`
	Revealed           bool   `json:"revealed"`
	Success            bool   `json:"success"`
	ProofTaskID        string `json:"proof_task_id"`
	ProofState         string `json:"proof_state"`
	Proof              string `json:"proof"`
	ProofSubmitTx      string `json:"proof_submit_tx"`
}

type ProofRequest struct {
	ReqID              string `json:"req_id"`
	AppID              string `json:"app_id"`
	Nonce              int64  `json:"nonce"`
	PublicValuesDigest string `json:"public_values_digest"`
	InputData          string `json:"input_data"`
	InputUrl           string `json:"input_url"`
	MaxFee             string `json:"max_fee"`
	MinStake           string `json:"min_stake"`
	Deadline           int64  `json:"deadline"`
	CreatedAt          int64  `json:"created_at"`
	Processed          bool   `json:"processed"`
}
