// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package dal

import (
	"context"
)

const addProofRequest = `-- name: AddProofRequest :exec
INSERT INTO proof_request (req_id, app_id, nonce, public_values_digest, input_data, input_url, max_fee, min_stake, deadline, created_at, processed)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type AddProofRequestParams struct {
	ReqID              string `json:"req_id"`
	AppID              string `json:"app_id"`
	Nonce              int64  `json:"nonce"`
	PublicValuesDigest string `json:"public_values_digest"`
	InputData          string `json:"input_data"`
	InputUrl           string `json:"input_url"`
	MaxFee             string `json:"max_fee"`
	MinStake           string `json:"min_stake"`
	Deadline           int64  `json:"deadline"`
	CreatedAt          int64  `json:"created_at"`
	Processed          bool   `json:"processed"`
}

func (q *Queries) AddProofRequest(ctx context.Context, arg AddProofRequestParams) error {
	_, err := q.db.ExecContext(ctx, addProofRequest,
		arg.ReqID,
		arg.AppID,
		arg.Nonce,
		arg.PublicValuesDigest,
		arg.InputData,
		arg.InputUrl,
		arg.MaxFee,
		arg.MinStake,
		arg.Deadline,
		arg.CreatedAt,
		arg.Processed,
	)
	return err
}

const findNotProcessedProofRequests = `-- name: FindNotProcessedProofRequests :many
SELECT req_id, app_id, nonce, public_values_digest, input_data, input_url, max_fee, min_stake, deadline, created_at, processed FROM proof_request
WHERE processed = false
`

func (q *Queries) FindNotProcessedProofRequests(ctx context.Context) ([]ProofRequest, error) {
	rows, err := q.db.QueryContext(ctx, findNotProcessedProofRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProofRequest
	for rows.Next() {
		var i ProofRequest
		if err := rows.Scan(
			&i.ReqID,
			&i.AppID,
			&i.Nonce,
			&i.PublicValuesDigest,
			&i.InputData,
			&i.InputUrl,
			&i.MaxFee,
			&i.MinStake,
			&i.Deadline,
			&i.CreatedAt,
			&i.Processed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findNotRegisteredApps = `-- name: FindNotRegisteredApps :many
SELECT app_id, img_url, registered FROM app
WHERE registered = false
`

func (q *Queries) FindNotRegisteredApps(ctx context.Context) ([]App, error) {
	rows, err := q.db.QueryContext(ctx, findNotRegisteredApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []App
	for rows.Next() {
		var i App
		if err := rows.Scan(&i.AppID, &i.ImgUrl, &i.Registered); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveApp = `-- name: SaveApp :exec
INSERT INTO app (app_id, img_url, registered )
VALUES ($1, $2, $3) ON CONFLICT DO NOTHING
`

type SaveAppParams struct {
	AppID      string `json:"app_id"`
	ImgUrl     string `json:"img_url"`
	Registered bool   `json:"registered"`
}

func (q *Queries) SaveApp(ctx context.Context, arg SaveAppParams) error {
	_, err := q.db.ExecContext(ctx, saveApp, arg.AppID, arg.ImgUrl, arg.Registered)
	return err
}

const selectMonitorBlock = `-- name: SelectMonitorBlock :one
SELECT event, block_num, block_idx, restart 
FROM monitor_block
WHERE event = $1
`

func (q *Queries) SelectMonitorBlock(ctx context.Context, event string) (MonitorBlock, error) {
	row := q.db.QueryRowContext(ctx, selectMonitorBlock, event)
	var i MonitorBlock
	err := row.Scan(
		&i.Event,
		&i.BlockNum,
		&i.BlockIdx,
		&i.Restart,
	)
	return i, err
}

const updateAppAsRegistered = `-- name: UpdateAppAsRegistered :exec
UPDATE app
SET registered = true
WHERE app_id = $1
`

func (q *Queries) UpdateAppAsRegistered(ctx context.Context, appID string) error {
	_, err := q.db.ExecContext(ctx, updateAppAsRegistered, appID)
	return err
}

const upsertMonitorBlock = `-- name: UpsertMonitorBlock :exec
INSERT INTO monitor_block (event, block_num, block_idx, restart) 
VALUES ($1, $2, $3, $4) ON CONFLICT (event) DO
UPDATE
SET block_num = excluded.block_num,
    block_idx = excluded.block_idx,
    restart = restart
`

type UpsertMonitorBlockParams struct {
	Event    string `json:"event"`
	BlockNum int64  `json:"block_num"`
	BlockIdx int64  `json:"block_idx"`
	Restart  bool   `json:"restart"`
}

func (q *Queries) UpsertMonitorBlock(ctx context.Context, arg UpsertMonitorBlockParams) error {
	_, err := q.db.ExecContext(ctx, upsertMonitorBlock,
		arg.Event,
		arg.BlockNum,
		arg.BlockIdx,
		arg.Restart,
	)
	return err
}
